### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by zbllbz6** [ziangcao0312/DiffTF#1]
why the generated models have no texture or color?

**Comment by ziangcao0312** [comment]
Our pre-trained generated models have texture. Can you provide more details?

**Comment by ziangcao0312** [comment]
Do you mean that the mesh files have no texture?

**Comment by zbllbz6** [comment]
yes, the mesh files have no texture

**Comment by ziangcao0312** [comment]
Since we adopted the marching cube (following eg3d), the mesh files indeed have no texture. If you want the texture,  you can read the vertex in .ply files and use it as the input coordinate of MLP to get color.

**Comment by ziangcao0312** [comment]
Thanks for your attention. We will upgrade our code to meet this requirement. If you have no further questions, could you please close this issue?

**Comment by zbllbz6** [comment]
OK, looking forward to your updates!
