### ISSUE TITLE
Pretrained model availability

### ISSUE THREAD

**Issue by mzamini92** [ziangcao0312/DiffTF#4]
Hi,

Since it is trained on large GPUs I was wondering is there any pretrained ckpt of shared decoder for shapenet available? I appreciate if you can share them.

Regards

**Comment by ziangcao0312** [comment]
We have provided our model at https://entuedu-my.sharepoint.com/my?id=%2Fpersonal%2Fziang001%5Fe%5Fntu%5Fedu%5Fsg%2FDocuments%2Fdifftf%2Fcheckpoint&ga=1. Please check it
